name: Frontend CI/CD # workflow name

on: 
   workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REPOSITORY: ${{ vars.ECR_FRONTEND_REPOSITORY }}

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app/frontend

    steps:
      - name: Cloning code
        uses: actions/checkout@v7.0.0

      - name: Check Codebase
        run: ls
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.2
        with:
          audience: ${{ vars.AUDIENCE }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      - name: List S3 buckets
        run: aws s3 ls

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Set Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build \
          --build-arg REACT_APP_API_URL=${{ vars.API_URL }} \
          -t $ECR_REPOSITORY:$IMAGE_TAG \
          -t $ECR_REPOSITORY:latest \
          .
      - name: List Images - 1
        run: | 
           docker images
           
      - name: Tag Image
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

          docker tag $ECR_REPOSITORY:latest \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest
      
      - name: List Images - 2
        run: | 
           docker images

      - name: Push Image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest
          
  deploy:
     name: Deploy Frontend
     needs: build
     runs-on: ubuntu-latest
     steps:
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
           aws-region: ${{ vars.AWS_REGION }}
   
       - name: Update SSM Parameter
         run: |
           aws ssm put-parameter \
             --name "/${{ vars.ENVIRONMENT }}/${{ vars.PROJECT_NAME }}/frontend/image_tag" \
             --value "${{ env.DOCKER_IMAGE }}" \
             --type String \
             --overwrite
   
       - name: Start Instance Refresh
         run: |
           aws autoscaling start-instance-refresh \
             --auto-scaling-group-name "${{ vars.FRONTEND_ASG_NAME }}" \
             --preferences '{
               "MinHealthyPercentage":100,
               "InstanceWarmup":90
             }'
   
       - name: Wait for Instance Refresh
         run: |
           REFRESH_ID=$(aws autoscaling describe-instance-refreshes \
             --auto-scaling-group-name "${{ vars.FRONTEND_ASG_NAME }}" \
             --query "InstanceRefreshes[0].InstanceRefreshId" \
             --output text)
   
           echo "Refresh ID: $REFRESH_ID"
   
           while true
           do
             STATUS=$(aws autoscaling describe-instance-refreshes \
               --auto-scaling-group-name "${{ vars.FRONTEND_ASG_NAME }}" \
               --instance-refresh-ids $REFRESH_ID \
               --query "InstanceRefreshes[0].Status" \
               --output text)
   
             echo "Current Status: $STATUS"
   
             if [ "$STATUS" = "Successful" ]; then
               echo "Deployment Successful"
               exit 0
             fi
   
             if [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Cancelled" ]; then
               echo "Deployment Failed"
               exit 1
             fi
   
             sleep 30
           done
